### PR TITLE
This is a PR which condenses a single paragraph

### PR DESCRIPTION
**Pull request by davidlmobley**
@nhenriksen - sorry to be confusing in terms of PRs, but this is a PR to my branch (which itself has a PR to your branch). It proposes some edits to condense a paragraph. I've set it up this way because I wanted to make it easy for you to reject THIS PR if you don't like how I condensed the paragraph and want to condense it yourself in a different way. 

If you DO like my changes, then you would want to:
1) Merge this PR first, then
2) Merge my other PR
(for the easiest merge process, at least). 

But, feel free to reject this one and edit the paragraph in question (see comments in the TeX about what I was trying to do) if you don't like what I've done. :)

### CODE REVIEW

**Review by nhenriksen — APPROVED** [review]
Looks fine.  I wrote it intentionally detailed, with the idea that we could pare it back.

**Comment by davidlmobley** [comment]
Boarding and I can't merge this from mobile, so it'll have to wait unless you guys can.

**Comment by nhenriksen** [comment]
in progress

**Comment by davidlmobley** [comment]
Thanks, @nhenriksen !

**Pull request merged**
