### PR TITLE
Update/reorganize input files for BRD4(1); rename ligands in tables for consistency with rest of table

### PR DESCRIPTION
**Pull request by GHeinzelmann**

### CODE REVIEW

**Comment by jchodera** [comment]
@GHeinzelmann : Do you have to create a separate commit for each file deleted? This ends up spamming everyone watching the repo with dozens of notification emails.

**Comment by GHeinzelmann** [comment]
Oh sorry about that! I was looking for a way to delete them all at the same time, but I think it is not possible in the web version, so I had to do it one at a time. I did not know that you received e-mails for every one deleted, sorry about spamming your account! Now I am done replacing the files, but I'll do it differently next time.

**Comment by davidlmobley** [comment]
Try the command-line interface, @GHeinzelmann , or if you really don't like that, the GUI version. Anything but the web interface. :)

**Comment by GHeinzelmann** [comment]
Yes, actually I am fine working in the command line in my computer, since I was using it to pull the files from my branch using git pull. A quick look online and now I have learned the git commit and the git push commands, so now I can make the changes in my computer and avoid these "quick and dirty" solutions from the web interface. Just made a test on the README file and it worked, so no more e-mail spams! :-)

**Comment by GHeinzelmann** [comment]
OK so the pdb, sdf and mol2 files are ready to be merged to the master branch. It took a few days since I was discussing with @nhenriksen the best way to prepare the input files so that they are consistent between the guest-host and protein-ligand systems. 

Also, should I make a table like in Niel's CD sets, with the experimental binding free energies for all ligands, and include it in the input files folder? Most of the information on the BRD4 ligands is already covered in Table 7 from the main paper, so I was wondering if we should include one in the input files as well.

**Comment by davidlmobley** [comment]
@GHeinzelmann -- thanks for your work on this!
> Also, should I make a table like in Niel's CD sets, with the experimental binding free energies for all ligands, and include it in the input files folder? Most of the information on the BRD4 ligands is already covered in Table 7 from the main paper, so I was wondering if we should include one in the input files as well.

If you don't mind, this would probably be helpful -- I think we want to progress in a direction where people can easily machine-parse the data they need out of the repo rather than having to pull things from tables in the paper. 

Aside from that, is this ready to merge? I'll have some time to review things tomorrow and am going to try and look at Niel's PR then; maybe I can do this at the same time if it's ready.

**Comment by GHeinzelmann** [comment]
Yes aside from the table it is ready to merge, I checked all the input files and I believe everything is OK. The table shouldn't take long to finish, it will probably be done by tomorrow since I can use Niel's as a template.

**Comment by GHeinzelmann** [comment]
Just finished the table with the experimental/theoretical info for all the ligands, I believe it is ready to merge, pending a final review.

**Comment by davidlmobley** [comment]
Thanks, @GHeinzelmann ! I'll hopefully have a look late today.

**Comment by davidlmobley** [comment]
@GHeinzelmann - we just merged #47 so you'll need to update this one (e.g. `git pull origin master`, resolve any conflicts (hopefully not any or minimal), then commit and push). LMK if you need help. 

I'm hoping to review shortly today, though we'll see if I really manage to get to it -- a couple other things to edit first.

**Comment by GHeinzelmann** [comment]
No problem, I'll update my branch so it is identical to master, and include these last changes as well. I I think I should be OK, I'll just backup all my files and then make a few tests using git. Unfortunately I am away today, but I`ll get to it tomorrow so it is ready as soon as possible.

**Review by davidlmobley — APPROVED** [review]
Looks good, @GHeinzelmann . Should be good to merge once conflicts are resolved. This should be quick/easy (it looks like the only conflict is the PDF so you'll just be pulling master and then updating the PDF), but let me know if you want me to do it instead.

The one thing that should still be changed before merging (or after) is to update the README.md to list the changes made here as changes not yet in a release. :)

**Comment by davidlmobley** [comment]
Big picture on this PR for the record, if I've got it right:
- It reorganizes data files
- Improves BRD4(1) README
- Switches sd files to sdf files
- Gives each BRD4(1) ligand a unique, paper-specific ligand identifier

**Comment by GHeinzelmann** [comment]
I think I can give it a go, but I'll let you know if I have any problems merging the branches. I did not get the second part on how I should update the README.md file. I got a little confused in the changes not made in a release part, and how should I add these changes to the README file.

I think the list in the second comment covers the changes I made to the README and the files, so the big picture part looks OK. Thanks for reviewing the files and for the comments, :)

**Comment by davidlmobley** [comment]
I'll take care of the README changes, @GHeinzelmann , and tag you so you can see what I do and know for the next time. I'll do it in a separate PR.

**Comment by GHeinzelmann** [comment]
OK thanks, sorry for not knowing what you meant and not being able to make the changes right away.

**Comment by GHeinzelmann** [comment]
I'll keep an eye on the new PR to know how it works the next time! :)

**Pull request merged**
